### ISSUE TITLE
gatsby link reloads page

### ISSUE THREAD

**Issue by humbertqz** [wiziple/gatsby-plugin-intl#30]
Hi thanks for your help, using the lang switcher the page switch smoothly, but for the Links in my nav when clicking one the page seems to do a reload. Is there a way to change this? 

This is an example of a link on my website:

`<Link to="/"><img src={logo} width="145" height="39" className="img-fluid"/></Link>`

**Comment by Kevinnko** [comment]
Hello, same issue for me:
`<Link className="menu-link" to="/product">`
Is this due to redirection ?

**Comment by Kevinnko** [comment]
Hey @humbertqz , I managed to solve my problem of the pages being reloaded by adding the current locale in the Link 'to' parameter, like this : 

`<Link className="menu-link" to={`/${currentLocale}/product`}>`

In order to access to currentLocale, just use the `<IntlContextConsumer>` component just as in the language.js file .

I hope this will help !

**Comment by humbertqz** [comment]
@Kevinnko  i missed this part in the docs. You need to use the Link component provided by the plugin, not the gatsby link component.
